site_name: pysymmetry
repo_url: https://github.com/ldsufrpe/pysymmetry 
site_description: Documentação da biblioteca pysymmetry.
site_author: Leon Silva, Marcelo Pedro

# Config do Theme and Plugins
theme:
  name: material


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../] 