# Informações do Projeto
site_name: pysymmetry
site_description: Documentação da biblioteca pysymmetry.
site_author: Seu Nome

# Configuração do Tema e Plugins
theme:
  name: material


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../] # Adicione esta linha